### ISSUE TITLE
Cache Expiration

### ISSUE THREAD

**Issue by robotiv** [djherbis/fscache#1]
It would be nice to be able to specify a cache expiration during initialization via "New". Value could be in hours and should persist after a program reload, possibly utilizing the last accessed file info on the items in the cache.

Is it also safe to assume you can create multiple caches simultaneously, as long as there's another "New" call with a different directory specified?

Cheers!

**Comment by djherbis** [comment]
Multiple caches (created with New) are safe to use concurrently, so long as they have different backing directories. 

I'm working on adding an expiry this evening, I'll post back here when its up.

**Comment by djherbis** [comment]
cache expiration has been added

**Comment by robotiv** [comment]
Thanks, that was fast
