### ISSUE TITLE
Ignore missing files/cache keys

### ISSUE THREAD

**Issue by T4cC0re** [djherbis/fscache#13]
Hi!

Currently fscache will return an error on `Get` of a cache key whose underlying file has been removed. I think it should handle this case gracefully and act like the cache key just is not there.

This can be triggered, e.g. by running `c.Clean()` on a instance of `Cache` or deleting a file manually.

**Comment by djherbis** [comment]
Nice catch! This was a bug, Clean() => RemoveAll() was not re-creating the root directory of the cache, which meant attempts to create files there were failing.

Just pushed a fix.
