### ISSUE TITLE
Provide a way to get the size of file in cache

### ISSUE THREAD

**Issue by deluan** [djherbis/fscache#16]
First of all, thanks for this awesome library. I started to implement a half-baked solution in my [Music Streamer](https://github.com/deluan/navidrome), but your library is great!

I'm using it to cache transcoded music. When it is the first time the client is requesting the music file, it is ok to not provide ranges/content-length, as there's no way to know beforehand what will be the size of the transcoded file when using VBR. But I'd like to be able to support ranges when the the file is already cached. For that I just need the size of the cached file. 

I see you made some progress on #6 that could help with this, is that available now? I couldn't find a way to get the stream size using this library API.

**Comment by djherbis** [comment]
Hey I'll see if I can get this added, should just be a matter of exposing a few things.

**Comment by djherbis** [comment]
Just pushed some stuff to expose it.

Should loosely be accessible via:
```
r, _, _ := cache.Get(key)
cr, ok := r.(*fscache.CacheReader)
if !ok {
  // you're not using the *FSCache type.
}
 
size, final, err := cr.Size()
// handle err, may indicate that this is a non-standard Cache FS.
if final {
  // size is finalized:
  sr := io.NewSectionReader(r, 0, size)
  http.ServeContent(..., sr)
}
```

**Comment by deluan** [comment]
Great! Thanks for the quick response. Will try it tomorrow and let you know how it goes

**Comment by deluan** [comment]
Seems to be working well. Thanks!
