### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by deluan** [djherbis/fscache#17]
I'm not totally sure when and why this happens, but one user of my app is reporting this error:
```
panic: runtime error: invalid memory address or nil pointer dereference

 -> github.com/djherbis/fscache.(*handleCounter).inc
 ->   /go/pkg/mod/github.com/djherbis/fscache@v0.10.0/fscache.go:327

    github.com/djherbis/fscache.(*FSCache).newFile
      /go/pkg/mod/github.com/djherbis/fscache@v0.10.0/fscache.go:227
    github.com/djherbis/fscache.(*FSCache).Get
      /go/pkg/mod/github.com/djherbis/fscache@v0.10.0/fscache.go:154
    github.com/deluan/navidrome/engine.(*cover).Get
      /github/workspace/engine/cover.go:50
    github.com/deluan/navidrome/server/subsonic.(*MediaRetrievalController).GetCoverArt
      /github/workspace/server/subsonic/media_retrieval.go:43
    github.com/deluan/navidrome/server/subsonic.H.func1
      /github/workspace/server/subsonic/api.go:138
    net/http.HandlerFunc.ServeHTTP
      /usr/local/go/src/net/http/server.go:2012
    github.com/go-chi/chi.(*ChainHandler).ServeHTTP
      /go/pkg/mod/github.com/go-chi/chi@v4.1.0+incompatible/chain.go:31
    github.com/go-chi/chi.(*Mux).routeHTTP
      /go/pkg/mod/github.com/go-chi/chi@v4.1.0+incompatible/mux.go:431
    net/http.HandlerFunc.ServeHTTP
      /usr/local/go/src/net/http/server.go:2012
    github.com/deluan/navidrome/server/subsonic.authenticate.func1.1
      /github/workspace/server/subsonic/middlewares.go:93
    net/http.HandlerFunc.ServeHTTP
      /usr/local/go/src/net/http/server.go:2012
    github.com/deluan/navidrome/server/subsonic.checkRequiredParameters.func1
      /github/workspace/server/subsonic/middlewares.go:63
    net/http.HandlerFunc.ServeHTTP
      /usr/local/go/src/net/http/server.go:2012
    github.com/deluan/navidrome/server/subsonic.postFormToQueryParams.func1
      /github/workspace/server/subsonic/middlewares.go:36
    net/http.HandlerFunc.ServeHTTP
      /usr/local/go/src/net/http/server.go:2012
    github.com/go-chi/chi.(*Mux).ServeHTTP
      /go/pkg/mod/github.com/go-chi/chi@v4.1.0+incompatible/mux.go:70
    github.com/deluan/navidrome/server/subsonic.(*Router).ServeHTTP
      /github/workspace/server/subsonic/api.go:48
    github.com/go-chi/chi.(*Mux).Mount.func1
      /go/pkg/mod/github.com/go-chi/chi@v4.1.0+incompatible/mux.go:298
    net/http.HandlerFunc.ServeHTTP
      /usr/local/go/src/net/http/server.go:2012
    github.com/deluan/navidrome/server.RequestLogger.func1
      /github/workspace/server/middlewares.go:21
    net/http.HandlerFunc.ServeHTTP
```

You can see in the original report that the key files are being created, but the cache files are created with size 0.

Maybe I'm using it wrongly? 
https://github.com/deluan/navidrome/blob/master/engine/cover.go#L50

What other information can I give you to help pin this error down?

Original report: https://github.com/deluan/navidrome/issues/177

**Comment by djherbis** [comment]
Taking a look, this is very weird though, newFIle creates the cachedFile object (so it's not nil):
https://github.com/djherbis/fscache/blob/646777dbf69bd09ed75a75cf5fd5baeccfb7ae40/fscache.go#L224

And then calls inc, where it's failing on nil deref on:
https://github.com/djherbis/fscache/blob/646777dbf69bd09ed75a75cf5fd5baeccfb7ae40/fscache.go#L327

But that should not be nil because we're in newFile and literally just initialized it.

Is this reproducible with a specific setup? I'd like to do some debugging on it to figure out how this is possible.

**Comment by djherbis** [comment]
I suspect this is the problem:
https://stackoverflow.com/questions/28670232/atomic-addint64-causes-invalid-memory-address-or-nil-pointer-dereference

What's the specific Go build constraints that produces this situation? I'm guessing alignment is messed up.

**Comment by 0xERR0R** [comment]
This error occurs on arm (raspberry pi 3)

**Comment by djherbis** [comment]
@0xERR0R Can you dump "go env" so I can match your build setup?

**Comment by 0xERR0R** [comment]
I used arm/v7 build from navidrome's release page. I guess, this will be built by [goreleaser](https://github.com/deluan/navidrome/blob/master/.goreleaser.yml)

**Comment by djherbis** [comment]
I gotta focus on my day job for awhile, but now that I've got enough details I work on fixing this tonight.

**Comment by 0xERR0R** [comment]
If you want to perform some test -> please contact me, I would be glad to help

**Comment by djherbis** [comment]
@0xERR0R @deluan I fixed this by adjusting the atomic field alignment as suspected.

To verify, I pulled the old version on my pi, ran go test and got the same panic. I fixed the alignment and re-ran go test a few times, no panic.

Let me know if this fixes things for you too :)

**Comment by deluan** [comment]
Thanks for the quick turnaround on this issue!
