### ISSUE TITLE
Closed connection

### ISSUE THREAD

**Issue by jhemmmm** [djherbis/fscache#18]
Hello,

fscache still keeps downloading the file even thou the request has been closed.

**Comment by djherbis** [comment]
Are you closing the stream? Note that the writer side usually would keep downloading so that the req is cached for next time.

**Comment by jhemmmm** [comment]
> Are you closing the stream? Note that the writer side usually would keep downloading so that the req is cached for next time.

I am closing the stream, but that's the problem there, the writer keeps downloading even thou the stream is already closed. Is it possible to close it too, and then instead of re-downloading the failed cache file, continue it's download instead?.

**Comment by djherbis** [comment]
You're only closing the reader I'm assuming not the writer.

The writer expects there to be 0-N readers that can leave/join the stream at basically any time.

You could pause writing when there's no readers I guess, but that's a bit against the spirit of caching I think. What's the main benefit in pausing in this situation? Is it unlikely another reader will come along wanting that stream?

**Comment by jhemmmm** [comment]
> You're only closing the reader I'm assuming not the writer.
> 
> The writer expects there to be 0-N readers that can leave/join the stream at basically any time.
> 
> You could pause writing when there's no readers I guess, but that's a bit against the spirit of caching I think. What's the main benefit in pausing in this situation? Is it unlikely another reader will come along wanting that stream?

Not you mentioned it that there might be another reading along the stream. My main point on this issue is to optimize my server's network bandwidth. Is there any possible suggestion you can make to get this done?.
