### ISSUE TITLE
nil pointer dereference fscache.go:60

### ISSUE THREAD

**Issue by robotiv** [djherbis/fscache#2]
After the cache starts up and creates the directories, I tried going to cd into them and got a permission denied error. Then when doing a "Get", there was a nil pointer dereference at:
src/github.com/djherbis/fscache/fscache.go:60

The test program runs as the same user that was trying to cd into the directories. There is some sort of permission issue when creating the directory. I think the directory needs execute permission to be openable under unix, ie. created with 0755.

**Comment by djherbis** [comment]
The nil ptr deref should be fixed. You can now specify the directory's perms when you create the cache. Let me know if you run into a similar problem with files.

**Comment by robotiv** [comment]
Great!
